access_token = "bfd05fec-a0da-47a5-869f-aa84b8c887a3"
device_id = "fb6922c2-fd57-4e9e-aa70-f0a1f8cce085"
license_key = "0976vHAf-UoQ235j9-43Oq57mD"
private_key = "EBbQiTwTFqUkKa6Wg1jOpowZJFsF4SukKbyNJCYw9G8="
